language: python
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
addons:
    firefox: "28.0"
install:
  - "bash install-bmp.sh"
  - "pip install -r requirements.txt"
script: python test_harprofiler.py
