browsermob_dir: ./browsermob-proxy-2.1.0-beta-4
har_dir: ./hars
# harstorage_url: http://localhost:5000
label_prefix:
login_user:
login_password:
run_cached: true
urls:
- https://www.edx.org
- https://www.edx.org/course-search
virtual_display: true
virtual_display_size_x: 1024
virtual_display_size_y: 768
