browsermob_dir: ./browsermob-proxy-2.1.0-beta-4
har_dir: ./test_hars
harstorage_url: http://edx.mockharstorage.com
label_prefix: testprefix-
run_cached: true
urls:
- https://www.example.com
virtual_display: true
virtual_display_size_x: 1024
virtual_display_size_y: 768
